# Generated by Django 4.1.5 on 2023-01-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookit_app', '0002_category_ingredient_recipe_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_img',
        ),
    ]
